import type { Chapter } from '@/types/curriculum'

const chapters: Chapter[] = [
  {
    id: 'math-6-1',
    subject: 'math',
    grade: 6,
    chapter: 1,
    title: 'จำนวนเต็ม',
    icon: '🔢',
    slug: 'integers',
    explain: [
      { type: 'text', html: '<p><strong>จำนวนเต็ม</strong> ประกอบด้วย:<br/>• จำนวนเต็มบวก: 1, 2, 3, ...<br/>• จำนวนเต็มศูนย์: 0<br/>• จำนวนเต็มลบ: -1, -2, -3, ...</p><p>บนเส้นจำนวน: จำนวนเต็มลบอยู่ซ้ายของ 0 จำนวนเต็มบวกอยู่ขวา</p>' },
      { type: 'highlight', text: '|-5| = 5 (ค่าสัมบูรณ์ = ระยะห่างจาก 0 เสมอเป็นบวก)' },
      { type: 'interactive', component: 'NumberLine', config: { min: -10, max: 10, step: 1, initialValue: 0 } },
      { type: 'example', text: 'อุณหภูมิ -3°C หมายถึง 3 องศาต่ำกว่าจุดเยือกแข็ง | หนี้สิน -500 บาท = ขาดทุน 500 บาท' },
    ],
    demo: {
      component: 'NumberLine',
      config: { min: -10, max: 10, step: 1, initialValue: 0 },
      steps: [
        { instruction: 'เส้นจำนวนขยายไปทางซ้าย — ลากไปที่ -5', config: { targetValue: -5 } },
        { instruction: '-3 + 7 = ? เริ่มที่ -3 เลื่อนขวา 7 ก้าว', config: { initialValue: -3, targetValue: 4 } },
        { instruction: '5 – 8 = ? เริ่มที่ 5 เลื่อนซ้าย 8 ก้าว', config: { initialValue: 5, targetValue: -3 } },
        { instruction: 'ค่าสัมบูรณ์: |-7| = 7 (ระยะห่างจาก 0)', config: { initialValue: -7, targetValue: 0 } },
      ],
    },
    practice: [
      { type: 'slider', q: 'ลากหา -3 + 8 = ?', min: -5, max: 10, step: 1, ans: 5, unit: '', hint: 'เริ่มที่ -3 เลื่อนขวา 8 ก้าว' },
      { type: 'fill', q: '|-9| = ?', ans: '9', hint: 'ค่าสัมบูรณ์ = ระยะห่างจาก 0' },
      { type: 'mc', q: 'จำนวนใดมากที่สุด?', opts: ['-1', '-5', '0', '-10'], ans: 2, hint: 'บนเส้นจำนวน 0 อยู่ขวากว่าจำนวนลบทุกตัว' },
      { type: 'fill', q: '-4 + (-3) = ?', ans: '-7', hint: 'บวกจำนวนลบ = ลบออก' },
      { type: 'fill', q: '5 – (-2) = ?', ans: '7', hint: 'ลบลบ = บวก' },
      { type: 'mc', q: 'อุณหภูมิ -5°C เพิ่ม 12°C เป็น?', opts: ['7°C', '17°C', '-7°C', '-17°C'], ans: 0, hint: '-5+12=?' },
      { type: 'fill', q: '(-3) × 4 = ?', ans: '-12', hint: 'ลบ × บวก = ลบ' },
      { type: 'fill', q: '(-6) ÷ (-2) = ?', ans: '3', hint: 'ลบ ÷ ลบ = บวก' },
      { type: 'mc', q: 'ระดับน้ำทะเล -30 ม. กับ -15 ม. ระดับใดสูงกว่า?', opts: ['-30 ม.', '-15 ม.', 'เท่ากัน', 'บอกไม่ได้'], ans: 1, hint: '-15 อยู่ขวากว่า -30 บนเส้นจำนวน' },
      { type: 'slider', q: '-8 + 3 = ?', min: -6, max: -4, step: 1, ans: -5, unit: '', hint: '-8 เลื่อนขวา 3 ก้าว' },
    ],
  },
  {
    id: 'math-6-2',
    subject: 'math',
    grade: 6,
    chapter: 2,
    title: 'เศษส่วน ทศนิยม และร้อยละ',
    icon: '🔄',
    slug: 'fractions-decimals-percent',
    explain: [
      { type: 'text', html: '<p>ทั้งสามรูปแบบแทนค่าเดียวกัน:<br/>• 1/4 = 0.25 = 25%<br/>• 3/5 = 0.60 = 60%<br/>• 7/8 = 0.875 = 87.5%</p><p>แปลง: เศษส่วน → ทศนิยม (หารเศษด้วยส่วน)<br/>ทศนิยม → ร้อยละ (× 100)</p>' },
      { type: 'highlight', text: '1/3 ≈ 0.333... (ทศนิยมไม่สิ้นสุด) — ระวังการปัดเศษ' },
      { type: 'interactive', component: 'FractionCutter', config: { maxParts: 10, initialParts: 4, initialFilled: 3, readOnly: true } },
      { type: 'example', text: 'ลด 20%: คูณด้วย 0.80 | เพิ่ม 15%: คูณด้วย 1.15' },
    ],
    demo: {
      component: 'FractionCutter',
      config: { maxParts: 10, initialParts: 5, initialFilled: 3 },
      steps: [
        { instruction: 'แสดง 3/5 — แบ่ง 5 ส่วน เลือก 3', config: { targetParts: 5, targetFilled: 3 } },
        { instruction: '3/5 = 0.6 = 60% — เห็นได้ 3 ใน 5 ชิ้น = 60% ของวงกลม' },
        { instruction: 'ปรับเป็น 75%: ต้องแสดงเป็น 3/4', config: { targetParts: 4, targetFilled: 3 } },
        { instruction: 'แสดง 1/3 ≈ 33.3% — แบ่ง 3 เลือก 1', config: { targetParts: 3, targetFilled: 1 } },
      ],
    },
    practice: [
      { type: 'fill', q: '3/8 = ?%', ans: '37.5', hint: '3÷8×100=?' },
      { type: 'fill', q: '0.625 เขียนเป็นเศษส่วนอย่างต่ำ = ?', ans: '5/8', hint: '625/1000 ลดรูป' },
      { type: 'mc', q: '7/20 = ?%', opts: ['3.5%', '35%', '70%', '350%'], ans: 1, hint: '7÷20×100=?' },
      { type: 'fill', q: 'ลด 30%: ราคาเดิม 600 บาท จ่ายจริง?', ans: '420', hint: '600×0.7=?' },
      { type: 'slider', q: '2/5 = ?%', min: 35, max: 45, step: 5, ans: 40, unit: '%', hint: '2÷5×100=?' },
      { type: 'fill', q: 'VAT 7%: สินค้า 200 บาท รวม VAT = ?', ans: '214', hint: '200×1.07=?' },
      { type: 'mc', q: 'ใหญ่กว่า: 5/6, 0.82, 83%?', opts: ['5/6', '0.82', '83%', 'เท่ากัน'], ans: 2, hint: '5/6≈83.3% > 83% > 82%' },
      { type: 'fill', q: 'ลด 25% แล้วเพิ่ม 25% ราคาสุดท้าย = ?% ของราคาเดิม?', ans: '93.75', hint: '×0.75×1.25=0.9375=93.75%' },
      { type: 'fill', q: '0.004 = ?/1000', ans: '4', hint: '0.004 = 4/1000' },
      { type: 'mc', q: 'ถ้า 60% ของจำนวนหนึ่ง = 90 จำนวนนั้นคือ?', opts: ['54', '150', '60', '145'], ans: 1, hint: 'จำนวน = 90÷0.6 = ?' },
    ],
  },
  {
    id: 'math-6-3',
    subject: 'math',
    grade: 6,
    chapter: 3,
    title: 'อัตราส่วนและสัดส่วน',
    icon: '⚖️',
    slug: 'ratio-proportion',
    explain: [
      { type: 'text', html: '<p><strong>อัตราส่วน</strong> เปรียบเทียบสองจำนวน เขียน a:b<br/>3:4 หมายถึง ทุก 3 ส่วน ของ A ต่อ 4 ส่วน ของ B</p><p><strong>สัดส่วน</strong>: a/b = c/d → ad = bc (cross multiply)</p>' },
      { type: 'highlight', text: 'อัตราส่วนเท่ากัน: 2:3 = 4:6 = 10:15 (คูณหรือหารทั้งคู่ด้วยจำนวนเดียวกัน)' },
      { type: 'interactive', component: 'BalanceDrag', config: { readOnly: true, initialLeft: [10, 10], initialRight: [10, 10, 10] } },
      { type: 'example', text: 'แบ่งเงิน 500 บาท ในอัตราส่วน 2:3 → ส่วน A = 500×2/5 = 200, ส่วน B = 300' },
    ],
    demo: {
      component: 'BarChartDrag',
      config: {
        initialData: [
          { label: 'A', value: 20, color: '#4F80FF' },
          { label: 'B', value: 30, color: '#FF7A2F' },
        ],
        maxValue: 60,
        yLabel: 'ส่วน',
      },
      steps: [
        { instruction: 'กราฟแสดงอัตราส่วน A:B = 2:3 (20:30)' },
        { instruction: 'ลากให้ A=40, B=60 — อัตราส่วนยังเป็น 2:3 ไหม?' },
        { instruction: 'ถ้ารวม A+B=100 อัตราส่วน 2:3 → A=40, B=60' },
        { instruction: 'ทดสอบ: ลากแท่งเพื่อหา A:B = 1:4 โดยรวม = 50' },
      ],
    },
    practice: [
      { type: 'fill', q: 'เขียนอัตราส่วน 12:18 ในรูปอย่างต่ำ', ans: '2:3', hint: 'หาร GCD(12,18)=6' },
      { type: 'fill', q: 'ถ้า x/5 = 12/20 แล้ว x = ?', ans: '3', hint: 'cross multiply: 20x=60' },
      { type: 'mc', q: 'แบ่ง 280 บาท ในอัตราส่วน 3:4 ส่วนเล็กคือ?', opts: ['100', '110', '120', '130'], ans: 2, hint: '280÷7×3=?' },
      { type: 'fill', q: 'อัตราส่วน 5:8 ถ้าส่วนแรก = 25 ส่วนที่สอง = ?', ans: '40', hint: '25/5=5, 8×5=?' },
      { type: 'mc', q: 'แผนที่อัตราส่วน 1:50000 ระยะในแผนที่ 3 cm = จริงกี่ m?', opts: ['15,000 m', '1,500 m', '150,000 m', '150 m'], ans: 1, hint: '3×50000=150000 cm = 1500 m' },
      { type: 'fill', q: 'ส้ม:แอปเปิ้ล = 2:5 มีแอปเปิ้ล 35 มีส้มกี่ผล?', ans: '14', hint: 'ส้ม=35÷5×2=?' },
      { type: 'fill', q: 'ทำแยม: น้ำตาล:ผลไม้ = 1:3 ผลไม้ 600g ต้องใช้น้ำตาลกี่กรัม?', ans: '200', hint: '600÷3×1=?' },
      { type: 'mc', q: 'x:12 = 5:6 → x = ?', opts: ['10', '11', '12', '9'], ans: 0, hint: 'x×6=12×5, x=60÷6=?' },
      { type: 'slider', q: 'แบ่ง 90 ในอัตราส่วน 1:2 ส่วนใหญ่คือ?', min: 55, max: 65, step: 5, ans: 60, unit: '', hint: '90÷3×2=?' },
      { type: 'fill', q: 'เงินเดือน A:B = 3:5 ถ้า B ได้ 25,000 บาท A ได้กี่บาท?', ans: '15000', hint: '25000÷5×3=?' },
    ],
  },
  {
    id: 'math-6-4',
    subject: 'math',
    grade: 6,
    chapter: 4,
    title: 'พีชคณิตเบื้องต้น',
    icon: '🔣',
    slug: 'basic-algebra',
    explain: [
      { type: 'text', html: '<p><strong>พีชคณิต</strong>: ใช้ตัวอักษรแทนจำนวนที่ไม่ทราบค่า</p><p>• นิพจน์: 3x + 5<br/>• สมการ: 3x + 5 = 20<br/>• ตัวแปร: x, y, n<br/>• สัมประสิทธิ์: เลขนำหน้าตัวแปร</p>' },
      { type: 'highlight', text: 'รวมเทอมสำคัญ: 3x + 5x = 8x | 2x + 3y ≠ 5xy (ต้องเหมือนกันทุกอย่าง)' },
      { type: 'example', text: '5(2x – 3) = 5×2x – 5×3 = 10x – 15 (กฎการแจกแจง)' },
    ],
    demo: {
      component: 'BalanceDrag',
      config: {},
      steps: [
        { instruction: 'ตาชั่งแทนสมการ 2x + 3 = 11' },
        { instruction: 'ด้านขวา = 11, ด้านซ้าย = 3 + x + x ทำให้สมดุล', config: { initialRight: [10, 1] } },
        { instruction: 'ลบ 3 ออกจากทั้งสองด้าน: 2x = 8 → x = 4' },
        { instruction: 'แก้สมการ: 3x – 2 = 13 → 3x = 15 → x = 5' },
      ],
    },
    practice: [
      { type: 'fill', q: '4x + 3 = 19 → x = ?', ans: '4', hint: '4x=16, x=16÷4=?' },
      { type: 'fill', q: '7 – 2y = 1 → y = ?', ans: '3', hint: '2y=6, y=?' },
      { type: 'mc', q: '5(x+2) = 35 → x = ?', opts: ['4', '5', '7', '6'], ans: 1, hint: 'x+2=7, x=?' },
      { type: 'fill', q: '3a – 4 = 2a + 6 → a = ?', ans: '10', hint: '3a-2a=6+4, a=?' },
      { type: 'fill', q: 'แจกแจง: 2(3x + 4) = ?', ans: '6x+8', hint: '2×3x + 2×4 = ?' },
      { type: 'mc', q: 'รวมเทอม: 4x + 7 – 2x + 3 = ?', opts: ['2x+10', '6x+10', '2x–4', '9x'], ans: 0, hint: '(4-2)x + (7+3) = ?' },
      { type: 'slider', q: 'n/3 + 2 = 7 → n = ?', min: 13, max: 17, step: 1, ans: 15, unit: '', hint: 'n/3=5, n=?' },
      { type: 'fill', q: 'ความยาวสี่เหลี่ยม = 2x+1 กว้าง = x ถ้า x=4 พื้นที่ = ?', ans: '36', hint: '(2×4+1)×4=9×4=?' },
      { type: 'mc', q: 'ถ้า 2x = 10 แล้ว 5x = ?', opts: ['25', '20', '50', '15'], ans: 0, hint: 'x=5, 5×5=?' },
      { type: 'fill', q: '(x+3)(x–3) = x² – ? (ผลต่างกำลังสอง)', ans: '9', hint: 'a²-b² = (a+b)(a-b), b=3, b²=?' },
    ],
  },
  {
    id: 'math-6-5',
    subject: 'math',
    grade: 6,
    chapter: 5,
    title: 'รูปเรขาคณิต 2 มิติ',
    icon: '🔷',
    slug: 'geometry-2d',
    explain: [
      { type: 'text', html: '<p>รูปสำคัญและสูตร:<br/>• วงกลม: A=πr², C=2πr<br/>• สามเหลี่ยม: A=½bh<br/>• สี่เหลี่ยมขนมเปียกปูน: A=½d₁d₂<br/>• สี่เหลี่ยมคางหมู: A=½(a+b)h</p>' },
      { type: 'highlight', text: 'π ≈ 3.14159 | ใช้ 3.14 ในการคำนวณ | C = 2πr = πd' },
      { type: 'interactive', component: 'ShapeMeasure', config: { shape: 'rectangle', initialWidth: 8, initialHeight: 6, maxWidth: 12, maxHeight: 10, unit: 'ซม.', readOnly: true } },
      { type: 'example', text: 'วงกลมรัศมี 7 ซม.: พื้นที่ = π×7² = 3.14×49 ≈ 153.86 ตร.ซม.' },
    ],
    demo: {
      component: 'ShapeMeasure',
      config: { shape: 'rectangle', initialWidth: 6, initialHeight: 4, maxWidth: 12, maxHeight: 10, unit: 'ซม.' },
      steps: [
        { instruction: 'ลากขอบเพื่อปรับรูปร่าง — ดูพื้นที่และเส้นรอบรูปเปลี่ยน' },
        { instruction: 'ทำให้พื้นที่ = 50 ตร.ซม. (เช่น 10×5)', config: { targetArea: 50 } },
        { instruction: 'ปรับเป็น shape สามเหลี่ยม แล้วดูสูตรพื้นที่' },
        { instruction: 'ลองหาขนาดที่ให้เส้นรอบรูป = 40 ซม. (สี่เหลี่ยมผืนผ้า)' },
      ],
    },
    practice: [
      { type: 'fill', q: 'วงกลมรัศมี 5 ซม. พื้นที่ ≈ ? (π=3.14)', ans: '78.5', hint: '3.14×5²=3.14×25=?' },
      { type: 'fill', q: 'วงกลมเส้นผ่าศูนย์กลาง 14 ซม. เส้นรอบวง ≈ ?', ans: '43.96', hint: 'C=π×14=3.14×14=?' },
      { type: 'mc', q: 'สี่เหลี่ยมคางหมู ด้านขนาน 8 และ 12 ซม. สูง 6 ซม. พื้นที่ = ?', opts: ['54', '60', '72', '48'], ans: 1, hint: '½(8+12)×6=?' },
      { type: 'fill', q: 'สี่เหลี่ยมขนมเปียกปูน เส้นทแยงมุม 10 และ 16 ซม. พื้นที่ = ?', ans: '80', hint: '½×10×16=?' },
      { type: 'slider', q: 'วงกลมรัศมี 3 ซม. เส้นรอบวง ≈ ?', min: 18, max: 20, step: 1, ans: 19, unit: 'ซม.', hint: '2×3.14×3=18.84≈19' },
      { type: 'fill', q: 'รูป L-shape: 10×8 ม. แต่ตัดมุมออก 3×4 ม. พื้นที่ = ?', ans: '68', hint: '10×8 – 3×4 = 80-12=?' },
      { type: 'mc', q: 'วงกลมรัศมี r พื้นที่ คือ? ถ้าเพิ่ม r เป็น 2r พื้นที่เป็น?', opts: ['2 เท่า', '4 เท่า', 'เท่าเดิม', '3 เท่า'], ans: 1, hint: 'π(2r)²=4πr²' },
      { type: 'fill', q: 'สวนรูปกึ่งวงกลม รัศมี 7 ม. พื้นที่ = ? (π≈3.14)', ans: '76.93', hint: '½×3.14×7²=?' },
      { type: 'mc', q: 'สี่เหลี่ยมจัตุรัสพื้นที่ 144 ตร.ซม. เส้นรอบรูป = ?', opts: ['36', '48', '60', '12'], ans: 1, hint: 'ด้าน=12, 4×12=?' },
      { type: 'fill', q: 'สามเหลี่ยมด้านเท่าทั้ง 3 ด้าน 6 ซม. สูง 5.2 ซม. พื้นที่ = ?', ans: '15.6', hint: '½×6×5.2=?' },
    ],
  },
  {
    id: 'math-6-6',
    subject: 'math',
    grade: 6,
    chapter: 6,
    title: 'รูปเรขาคณิต 3 มิติ',
    icon: '🧊',
    slug: 'geometry-3d',
    explain: [
      { type: 'text', html: '<p>รูปทรง 3 มิติสำคัญ:<br/>• <strong>ทรงลูกบาศก์</strong>: V=a³, SA=6a²<br/>• <strong>ทรงสี่เหลี่ยมมุมฉาก</strong>: V=lwh, SA=2(lw+lh+wh)<br/>• <strong>ทรงกระบอก</strong>: V=πr²h, SA=2πr(r+h)<br/>• <strong>ทรงกรวย</strong>: V=⅓πr²h</p>' },
      { type: 'highlight', text: 'ทรงกลม: V=⁴⁄₃πr³, SA=4πr²' },
      { type: 'interactive', component: 'CubeBuilder', config: { gridSize: 5, readOnly: false } },
      { type: 'example', text: 'ทรงกระบอก: r=3, h=10 → V=3.14×9×10=282.6 cm³' },
    ],
    demo: {
      component: 'CubeBuilder',
      config: { gridSize: 5 },
      steps: [
        { instruction: 'สร้างทรงที่มีปริมาตร 8 (2×2×2)', config: { targetVolume: 8 } },
        { instruction: 'สร้างทรงที่มีปริมาตร 16', config: { targetVolume: 16 } },
        { instruction: 'ปริมาตรเดียวกัน รูปร่างต่างกันได้ (4×4=16 หรือ 2×8=16)' },
        { instruction: 'ทดลอง: สร้าง 24 ลูก ด้วยแบบต่างๆ', config: { targetVolume: 24 } },
      ],
    },
    practice: [
      { type: 'fill', q: 'ทรงลูกบาศก์ด้าน 5 ซม. ปริมาตร = ?', ans: '125', hint: '5³=?' },
      { type: 'fill', q: 'กล่อง 4×5×6 ซม. พื้นที่ผิว = ?', ans: '148', hint: '2(4×5+4×6+5×6)=2(20+24+30)=?' },
      { type: 'mc', q: 'ทรงกระบอก r=4, h=5 ปริมาตร ≈ ? (π=3.14)', opts: ['251.2', '125.6', '502.4', '80'], ans: 0, hint: '3.14×16×5=?' },
      { type: 'fill', q: 'ทรงกรวย r=3, h=4 ปริมาตร = ? (π=3.14)', ans: '37.68', hint: '⅓×3.14×9×4=?' },
      { type: 'slider', q: 'กล่อง 10×10×10 ซม. ปริมาตร = ?', min: 990, max: 1010, step: 10, ans: 1000, unit: 'cm³', hint: '10³=?' },
      { type: 'fill', q: 'ถังน้ำทรงกระบอก r=50 cm h=100 cm บรรจุน้ำได้ ? ลิตร', ans: '785', hint: '3.14×50²×100=785,000 cm³=785 ลิตร' },
      { type: 'mc', q: 'ลูกบอลกลม r=7 ซม. SA ≈ ? (π=3.14)', opts: ['615.44', '307.72', '1,436', '153.86'], ans: 0, hint: '4×3.14×7²=?' },
      { type: 'fill', q: 'ทรงสี่เหลี่ยม กว้าง 6 ยาว 8 สูง 4 ปริมาตร = ?', ans: '192', hint: '6×8×4=?' },
      { type: 'mc', q: 'ปริมาตรทรงกรวยต่อทรงกระบอกที่มี r และ h เดียวกัน = ?', opts: ['1/2', '1/3', '2/3', '1/4'], ans: 1, hint: 'V_กรวย = ⅓ V_กระบอก' },
      { type: 'fill', q: 'แผ่นโลหะ 6 แผ่น แผ่นละ 100 cm² ทำกล่องลูกบาศก์ ด้านละ ? ซม.', ans: '10', hint: '6×ด้าน²=600, ด้าน²=100, ด้าน=?' },
    ],
  },
  {
    id: 'math-6-7',
    subject: 'math',
    grade: 6,
    chapter: 7,
    title: 'สมการเชิงเส้น',
    icon: '📊',
    slug: 'linear-equations',
    explain: [
      { type: 'text', html: '<p><strong>สมการเชิงเส้น</strong> มีตัวแปรกำลัง 1 เท่านั้น<br/>รูปแบบ: ax + b = c<br/>ขั้นตอน: ย้ายพจน์ → แยกตัวแปร → หาค่า</p><p>สมการสองตัวแปร: ax + by = c<br/>ต้องการ 2 สมการเพื่อแก้</p>' },
      { type: 'highlight', text: 'ตรวจสอบ: แทนค่าที่ได้กลับเข้าสมการทั้งหมด ทั้งสองด้านต้องเท่ากัน' },
      { type: 'interactive', component: 'BalanceDrag', config: { readOnly: false } },
      { type: 'example', text: 'แก้ 2x + 3 = x + 7 → ย้าย x: 2x-x=7-3 → x=4' },
    ],
    demo: {
      component: 'NumberLine',
      config: { min: -5, max: 15, step: 1, initialValue: 0 },
      steps: [
        { instruction: 'เส้นจำนวนช่วยแก้สมการ — x + 3 = 8 หมายถึงอยู่ที่ไหน?' },
        { instruction: 'เริ่มที่ 3 แล้วเลื่อนไปหา 8 → เลื่อน 5 ก้าว → x = 5', config: { initialValue: 3, targetValue: 8 } },
        { instruction: 'แก้ 2x = 10: x = 5 อยู่กึ่งกลางระหว่าง 0 กับ 10', config: { targetValue: 5 } },
        { instruction: 'แก้ x – 4 = -1: x = 3', config: { targetValue: 3 } },
      ],
    },
    practice: [
      { type: 'fill', q: '3x + 7 = 22 → x = ?', ans: '5', hint: '3x=15, x=?' },
      { type: 'fill', q: '5 – 2x = -3 → x = ?', ans: '4', hint: '-2x=-8, x=?' },
      { type: 'mc', q: '4(x–3) = 2(x+5) → x = ?', opts: ['10', '11', '12', '13'], ans: 1, hint: '4x-12=2x+10, 2x=22, x=?' },
      { type: 'fill', q: 'x/3 – 2 = 4 → x = ?', ans: '18', hint: 'x/3=6, x=?' },
      { type: 'fill', q: 'แก้ระบบ: x+y=10, x–y=4 → x=?, y=?', ans: 'x=7, y=3', hint: 'บวกสมการ: 2x=14, x=7, y=10-7=3' },
      { type: 'mc', q: '2x + y = 7 และ x + y = 4 → x = ?', opts: ['3', '4', '2', '1'], ans: 0, hint: 'ลบ: (2x+y)-(x+y)=7-4 → x=3' },
      { type: 'fill', q: 'อายุพ่อ = 3×อายุลูก อีก 10 ปีผลรวม = 60 อายุลูกตอนนี้ = ?', ans: '10', hint: 'ตั้งสมการ: ลูก=x, พ่อ=3x, (x+10)+(3x+10)=60' },
      { type: 'fill', q: '0.5x + 1.5 = 4 → x = ?', ans: '5', hint: '0.5x=2.5, x=?' },
      { type: 'slider', q: '3x – 5 = 4 → x = ?', min: 2, max: 4, step: 1, ans: 3, unit: '', hint: '3x=9, x=?' },
      { type: 'mc', q: 'ถ้า 2x + 3 > 11 แล้ว x > ?', opts: ['3', '4', '5', '6'], ans: 1, hint: '2x>8, x>4' },
    ],
  },
  {
    id: 'math-6-8',
    subject: 'math',
    grade: 6,
    chapter: 8,
    title: 'สถิติและการวิเคราะห์ข้อมูล',
    icon: '📈',
    slug: 'statistics-analysis',
    explain: [
      { type: 'text', html: '<p>การวิเคราะห์ข้อมูล:<br/>• <strong>Range</strong>: ค่าสูงสุด – ต่ำสุด<br/>• <strong>Mean</strong>: ค่าเฉลี่ย<br/>• <strong>Median</strong>: มัธยฐาน<br/>• <strong>Mode</strong>: ฐานนิยม<br/>• <strong>Variance/SD</strong>: ความแปรปรวน</p>' },
      { type: 'highlight', text: 'ข้อมูลเบ้: ใช้ Median ดีกว่า Mean | ข้อมูลสมมาตร: ทั้งสองใกล้เคียงกัน' },
      { type: 'example', text: 'เงินเดือน 5 คน: 15k, 16k, 18k, 20k, 100k → Mean=33.8k แต่ Median=18k (แสดงภาพที่แท้จริง)' },
    ],
    demo: {
      component: 'BarChartDrag',
      config: {
        initialData: [
          { label: 'Q1', value: 70 }, { label: 'Q2', value: 85 },
          { label: 'Q3', value: 60 }, { label: 'Q4', value: 90 }, { label: 'Q5', value: 75 },
        ],
        maxValue: 100,
        yLabel: 'คะแนน',
      },
      steps: [
        { instruction: 'กราฟแสดงคะแนน 5 ข้อ — หา Range (สูงสุด-ต่ำสุด)' },
        { instruction: 'Range = 90-60 = 30 | Mean = (70+85+60+90+75)÷5 = 76' },
        { instruction: 'เรียงข้อมูล: 60,70,75,85,90 → Median = 75' },
        { instruction: 'ลองปรับให้ค่าเฉลี่ยเท่ากับ 80 — ต้องเปลี่ยนค่าใดบ้าง?' },
      ],
    },
    practice: [
      { type: 'fill', q: 'ข้อมูล: 5,8,3,9,7,3,6 Range = ?', ans: '6', hint: '9-3=?' },
      { type: 'fill', q: 'คะแนน 6 ครั้ง รวม 480 ค่าเฉลี่ย = ?', ans: '80', hint: '480÷6=?' },
      { type: 'mc', q: 'ข้อมูล 7, 12, 15, 8, 12, 10 ฐานนิยม = ?', opts: ['7', '10', '12', '15'], ans: 2, hint: '12 ปรากฏ 2 ครั้ง มากที่สุด' },
      { type: 'fill', q: 'เรียงข้อมูล 6 ชุด: 3,5,7,8,10,12 มัธยฐาน = ?', ans: '7.5', hint: 'ค่าเฉลี่ยของตำแหน่งที่ 3 และ 4 = (7+8)÷2' },
      { type: 'slider', q: 'ต้องการ Mean = 70 จาก 4 ชุด ได้ไปแล้ว 65,72,68 ชุดสุดท้ายต้องได้ ?', min: 70, max: 80, step: 5, ans: 75, unit: '', hint: '4×70=280, 280-65-72-68=?' },
      { type: 'fill', q: 'ข้อมูล 2 ชุด A: mean=60, B: mean=80 รวม 10 ชุดเท่ากัน mean รวม = ?', ans: '70', hint: '(5×60+5×80)÷10=?' },
      { type: 'mc', q: 'ข้อมูล 1,2,3,4,100 ค่าใดที่ไม่เหมาะสมแสดงค่ากลาง?', opts: ['Median', 'Mode', 'Mean', 'Range'], ans: 2, hint: 'ค่าสุดโต่ง (100) ดึง Mean ให้เบ้' },
      { type: 'fill', q: 'คะแนนต่ำสุด 45 Range = 40 คะแนนสูงสุด = ?', ans: '85', hint: 'สูงสุด = ต่ำสุด + Range = ?' },
      { type: 'mc', q: 'ถ้าเพิ่มค่า 50 (= Mean) เข้าชุดข้อมูล Mean จะ?', opts: ['เพิ่มขึ้น', 'ลดลง', 'ไม่เปลี่ยน', 'เพิ่ม 50'], ans: 2, hint: 'เพิ่มค่าเท่า Mean → Mean ไม่เปลี่ยน' },
      { type: 'fill', q: 'ข้อมูล n ชุด Mean = 40 ถ้าทุกค่าเพิ่ม 5 Mean ใหม่ = ?', ans: '45', hint: 'Mean เปลี่ยนตามการเลื่อน' },
    ],
  },
  {
    id: 'math-6-9',
    subject: 'math',
    grade: 6,
    chapter: 9,
    title: 'ความน่าจะเป็น',
    icon: '🎲',
    slug: 'probability',
    explain: [
      { type: 'text', html: '<p><strong>ความน่าจะเป็น</strong> = จำนวนผลลัพธ์ที่ต้องการ ÷ จำนวนผลลัพธ์ทั้งหมด</p><p>ค่าอยู่ระหว่าง 0 ถึง 1:<br/>• 0 = เป็นไปไม่ได้<br/>• 1 = เป็นแน่นอน<br/>• 0.5 = โอกาสเท่ากัน</p>' },
      { type: 'highlight', text: 'P(เหตุการณ์) = n(A) / n(S) | P(A และ B) = P(A) × P(B) สำหรับเหตุการณ์อิสระ' },
      { type: 'example', text: 'โยนเหรียญ 1 ครั้ง: P(หัว) = 1/2 | ทอดลูกเต๋า: P(ได้ 3) = 1/6' },
    ],
    demo: {
      component: 'BarChartDrag',
      config: {
        initialData: [
          { label: 'หัว', value: 50, color: '#4F80FF' },
          { label: 'ก้อย', value: 50, color: '#FF7A2F' },
        ],
        maxValue: 100,
        yLabel: '%',
      },
      steps: [
        { instruction: 'โยนเหรียญ: หัว 50% ก้อย 50% (เหตุการณ์สมดุล)' },
        { instruction: 'ลากให้แท่งหนึ่งสูงกว่าอีกแท่ง — แต่รวมต้องเป็น 100%' },
        { instruction: 'ถ้าโยน 100 ครั้ง คาดว่าหัว 50 ก้อย 50 (ทฤษฎีความน่าจะเป็น)' },
        { instruction: 'ลูกเต๋า 6 หน้า: P(คู่) = 3/6 = 50% ลองปรับกราฟ' },
      ],
    },
    practice: [
      { type: 'fill', q: 'ทอดลูกเต๋า P(แต้ม > 4) = ?', ans: '1/3', hint: 'แต้ม 5,6 → 2 จาก 6 = 1/3' },
      { type: 'fill', q: 'ถุงมีลูกบอล แดง 3 เขียว 7 P(แดง) = ?', ans: '3/10', hint: '3/(3+7) = ?' },
      { type: 'mc', q: 'โยนเหรียญ 2 ครั้ง P(หัวทั้งคู่) = ?', opts: ['1/2', '1/3', '1/4', '1/8'], ans: 2, hint: '½ × ½ = ?' },
      { type: 'fill', q: 'P(A) = 0.3 P(A ไม่เกิด) = ?', ans: '0.7', hint: 'P(ไม่เกิด) = 1 – P(เกิด)' },
      { type: 'slider', q: 'ไพ่ 52 ใบ P(ดึงไพ่โพดำ) = ? (ไพ่โพดำมี 13 ใบ)', min: 20, max: 30, step: 5, ans: 25, unit: '%', hint: '13/52=1/4=25%' },
      { type: 'fill', q: 'สุ่มตัวเลข 1-20 P(ตัวเลขเป็นทวีคูณของ 3) = ?', ans: '3/10', hint: 'ทวีคูณ 3: 3,6,9,12,15,18 = 6 ตัว, 6/20=3/10' },
      { type: 'mc', q: 'เหตุการณ์ A: P=0.4, เหตุการณ์ B: P=0.3 (อิสระกัน) P(A และ B) = ?', opts: ['0.7', '0.12', '0.34', '0.1'], ans: 1, hint: 'P(A)×P(B)=0.4×0.3=?' },
      { type: 'fill', q: 'ทอดลูกเต๋า 2 ลูก P(ผลรวม=7) = ? (ทั้งหมด 36 กรณี)', ans: '1/6', hint: 'คู่ที่รวม=7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 กรณี' },
      { type: 'mc', q: 'ความน่าจะเป็นที่เป็นไปไม่ได้คือ?', opts: ['0', '0.5', '1', '-1'], ans: 0, hint: 'P=0 คือเหตุการณ์ที่เป็นไปไม่ได้' },
      { type: 'fill', q: 'ถุงมีลูกบอล n ลูก แดง 4 ลูก P(แดง)=0.2 n=?', ans: '20', hint: '4/n=0.2 → n=4/0.2=?' },
    ],
  },
  {
    id: 'math-6-10',
    subject: 'math',
    grade: 6,
    chapter: 10,
    title: 'เงินและการเงิน',
    icon: '💰',
    slug: 'money-finance',
    explain: [
      { type: 'text', html: '<p>คณิตศาสตร์การเงิน:<br/>• <strong>ดอกเบี้ยอย่างง่าย</strong>: I = P × r × t<br/>• <strong>ดอกเบี้ยทบต้น</strong>: A = P(1+r)ⁿ<br/>• <strong>กำไร/ขาดทุน</strong>: = ราคาขาย – ราคาทุน<br/>• <strong>% กำไร</strong>: กำไร/ทุน × 100</p>' },
      { type: 'highlight', text: 'P = เงินต้น, r = อัตราดอกเบี้ย, t = เวลา (ปี)' },
      { type: 'interactive', component: 'MoneyDrag', config: { availableDenominations: [1000, 500, 100, 50, 20] } },
      { type: 'example', text: 'ฝากเงิน 10,000 บาท ดอกเบี้ย 5% ต่อปี 3 ปี → I=10,000×0.05×3=1,500 บาท' },
    ],
    demo: {
      component: 'MoneyDrag',
      config: { availableDenominations: [1000, 500, 100, 50, 20, 10] },
      steps: [
        { instruction: 'รวมเงินให้ได้ 1,850 บาท ใช้ธนบัตรน้อยใบที่สุด', config: { targetTotal: 1850 } },
        { instruction: 'จ่าย 500 บาท ซื้อของ 285 บาท ทอนกี่บาท? (รวม 215)', config: { targetTotal: 215 } },
        { instruction: 'ออมเงิน: เดือนละ 800 บาท ปีละเท่าไร? (9,600)', config: { targetTotal: 9600 } },
        { instruction: 'ลองสร้างจำนวนที่ซับซ้อนขึ้น' },
      ],
    },
    practice: [
      { type: 'fill', q: 'ฝาก 5,000 บาท ดอกเบี้ย 4% ต่อปี 2 ปี ได้ดอกเบี้ยรวม?', ans: '400', hint: 'I=5000×0.04×2=?' },
      { type: 'fill', q: 'ซื้อของราคาทุน 200 บาท ขาย 250 บาท กำไร ?%', ans: '25', hint: '50/200×100=?' },
      { type: 'mc', q: 'เงินเดือน 15,000 บาท ออมไป 20% ใช้จ่ายจริง?', opts: ['12,000', '3,000', '13,000', '11,000'], ans: 0, hint: '15,000×0.8=?' },
      { type: 'fill', q: 'ซื้อหุ้นราคา 100 บาท ราคาเพิ่ม 15% ราคาปัจจุบัน?', ans: '115', hint: '100×1.15=?' },
      { type: 'slider', q: 'ขาย 450 บาท ขาดทุน 10% ราคาทุนคือ?', min: 490, max: 510, step: 5, ans: 500, unit: 'บาท', hint: 'ทุน×0.9=450, ทุน=450÷0.9=?' },
      { type: 'fill', q: 'ใช้ไฟฟ้า 250 หน่วย หน่วยละ 3.80 บาท ค่าไฟ?', ans: '950', hint: '250×3.80=?' },
      { type: 'mc', q: 'ฝาก 10,000 ดอกเบี้ยทบต้น 5% ปีละ 2 ปี ได้ทั้งหมด?', opts: ['11,000', '11,025', '10,500', '11,100'], ans: 1, hint: '10000×1.05²=10000×1.1025=?' },
      { type: 'fill', q: 'ส่วนลด 30% แล้วลดอีก 10% ราคา 1,000 บาท จ่ายจริง?', ans: '630', hint: '1000×0.7×0.9=?' },
      { type: 'fill', q: 'วางแผนซื้อของ 3,600 บาท ออมเดือนละ 300 บาท กี่เดือน?', ans: '12', hint: '3600÷300=?' },
      { type: 'mc', q: 'กำไร 800 บาท คิดเป็น 40% ของต้นทุน ต้นทุนคือ?', opts: ['1,600', '2,000', '1,800', '2,400'], ans: 1, hint: 'ทุน=800÷0.4=?' },
    ],
  },
  {
    id: 'math-6-11',
    subject: 'math',
    grade: 6,
    chapter: 11,
    title: 'ตรรกศาสตร์และการให้เหตุผล',
    icon: '🧠',
    slug: 'logic-reasoning',
    explain: [
      { type: 'text', html: '<p><strong>ตรรกศาสตร์</strong>: การให้เหตุผลอย่างมีระบบ</p><p>• ประพจน์ (Proposition): ข้อความที่จริงหรือเท็จอย่างใดอย่างหนึ่ง<br/>• การนิรนัย: จากหลักทั่วไปสู่กรณีเฉพาะ<br/>• การอุปนัย: จากกรณีเฉพาะสู่หลักทั่วไป</p>' },
      { type: 'highlight', text: 'เงื่อนไข: "ถ้า P แล้ว Q" จริงเมื่อ: P=จริง,Q=จริง หรือ P=เท็จ (ไม่ว่า Q จะเป็นอะไร)' },
      { type: 'example', text: '"ถ้าฝนตก ถนนเปียก" — ถนนเปียกไม่ได้หมายความว่าฝนตก (อาจมีสาเหตุอื่น)' },
    ],
    demo: {
      component: 'BalanceDrag',
      config: {},
      steps: [
        { instruction: 'ตาชั่งแสดงสมดุลของเหตุผล — ทั้งสองด้านต้องสมดุล' },
        { instruction: '"ทุกจำนวนคู่หารด้วย 2 ลงตัว" — ทดสอบ: 4÷2=2, 8÷2=4 ✓' },
        { instruction: '"จำนวนที่หารด้วย 2 ลงตัวเป็นจำนวนคู่" — จริงหรือเท็จ?' },
        { instruction: 'สรุปด้วยการให้เหตุผลสมบูรณ์' },
      ],
    },
    practice: [
      { type: 'mc', q: '"ถ้า x² = 9 แล้ว x = 3" ข้อความนี้จริงหรือเท็จ?', opts: ['จริงเสมอ', 'เท็จ (x=-3 ก็ได้)', 'ขึ้นอยู่กับ x', 'ไม่สามารถตัดสินได้'], ans: 1, hint: 'x²=9 → x=±3 ไม่ใช่แค่ 3' },
      { type: 'fill', q: '"จำนวนเฉพาะทั้งหมดเป็นจำนวนคี่" — ยกข้อยกเว้น?', ans: '2', hint: 'จำนวนเฉพาะที่เป็นจำนวนคู่มีอยู่ตัวเดียว' },
      { type: 'mc', q: 'จาก "A→B" และ "B→C" สรุปได้ว่า?', opts: ['A→C', 'C→A', 'B→A', 'ไม่สามารถสรุปได้'], ans: 0, hint: 'Syllogism: A→B, B→C → A→C' },
      { type: 'mc', q: 'ข้อใดเป็นประพจน์ (Proposition)?', opts: ['x + 3 = 7', '2+2=4', 'จงคำนวณ', 'ฝนตกไหม?'], ans: 1, hint: 'ประพจน์ต้องเป็นจริงหรือเท็จได้ชัดเจน' },
      { type: 'fill', q: 'ถ้า p จริง และ q เท็จ แล้ว "p และ q" มีค่า?', ans: 'เท็จ', hint: 'AND: จริงเมื่อทั้งคู่จริงเท่านั้น' },
      { type: 'mc', q: 'negation ของ "ทุก n เป็นจำนวนคู่" คือ?', opts: ['ทุก n เป็นจำนวนคี่', 'มีบาง n ที่ไม่เป็นจำนวนคู่', 'ไม่มี n ที่เป็นจำนวนคู่', 'บาง n เป็นจำนวนคู่'], ans: 1, hint: 'ปฏิเสธ "ทุก" = "มีบาง... ไม่..."' },
      { type: 'fill', q: 'p: "4 > 3" (จริง), q: "5 < 2" (เท็จ) → p OR q = ?', ans: 'จริง', hint: 'OR: จริงเมื่อมีอย่างน้อยหนึ่งตัวจริง' },
      { type: 'mc', q: '"ถ้าสามเหลี่ยมด้านเท่า แล้วมุมทุกมุม=60°" converse คือ?', opts: ['ถ้ามุมทุกมุม=60° แล้วเป็นสามเหลี่ยมด้านเท่า', 'ถ้าไม่ด้านเท่า แล้วมุมไม่เท่า 60°', 'ถ้ามุมไม่เท่า แล้วไม่ด้านเท่า', 'ด้านเท่า iff มุมเท่า'], ans: 0, hint: 'Converse: สลับ if-then' },
      { type: 'fill', q: 'รูปแบบ: 1, 1, 2, 3, 5, 8, ... ต่อไปคือ?', ans: '13', hint: 'Fibonacci: บวกสองตัวก่อนหน้า' },
      { type: 'mc', q: '"จำนวนทั้งหมดที่หารด้วย 6 ลงตัว ก็หารด้วย 3 ลงตัว" จริงหรือเท็จ?', opts: ['จริง', 'เท็จ', 'บางครั้งจริง', 'ขึ้นอยู่กับจำนวน'], ans: 0, hint: '6 = 2×3 ดังนั้นทุกผลคูณของ 6 มีปัจจัย 3' },
    ],
  },
  {
    id: 'math-6-12',
    subject: 'math',
    grade: 6,
    chapter: 12,
    title: 'การวัดและหน่วยวัด',
    icon: '📏',
    slug: 'measurement-units',
    explain: [
      { type: 'text', html: '<p>ระบบ SI และการแปลงหน่วย:<br/>• ความยาว: mm < cm < m < km<br/>• มวล: mg < g < kg < t<br/>• ปริมาตร: mL < L < kL<br/>• อุณหภูมิ: °C ↔ °F = °C×9/5+32</p>' },
      { type: 'highlight', text: 'คำนำหน้า: milli=0.001 | centi=0.01 | kilo=1000 | mega=1,000,000' },
      { type: 'example', text: '25°C = 25×9/5+32 = 45+32 = 77°F | 0°C = 32°F | 100°C = 212°F' },
    ],
    demo: {
      component: 'NumberLine',
      config: { min: 0, max: 100, step: 10, initialValue: 0 },
      steps: [
        { instruction: 'เส้นแสดงหน่วยเป็นซม. — แปลงค่าต่างๆ' },
        { instruction: '1 เมตร = 100 ซม. — ลากไปที่ 100', config: { targetValue: 100 } },
        { instruction: '0.5 เมตร = 50 ซม. — ลากไปที่ 50', config: { targetValue: 50 } },
        { instruction: 'วัดของจริงในห้องและแปลงหน่วย' },
      ],
    },
    practice: [
      { type: 'fill', q: '5.2 kg = ? g', ans: '5200', hint: '×1000' },
      { type: 'fill', q: '3,500 mL = ? L', ans: '3.5', hint: '÷1000' },
      { type: 'fill', q: '37°C = ?°F', ans: '98.6', hint: '37×9/5+32=66.6+32=?' },
      { type: 'mc', q: '2.5 km = ? m', opts: ['250', '2,500', '25,000', '25'], ans: 1, hint: '×1000' },
      { type: 'fill', q: '0.45 m = ? cm', ans: '45', hint: '×100' },
      { type: 'slider', q: '100°C = ?°F', min: 210, max: 215, step: 1, ans: 212, unit: '°F', hint: '100×9/5+32=180+32=?' },
      { type: 'fill', q: '1 ตันเมตริก = ? kg', ans: '1000', hint: '1 t = 1,000 kg' },
      { type: 'mc', q: '0°C = ?°F', opts: ['32', '0', '100', '212'], ans: 0, hint: '0×9/5+32=32' },
      { type: 'fill', q: '2 ชั่วโมง 30 นาที 15 วินาที = ? วินาที', ans: '9015', hint: '2×3600+30×60+15=7200+1800+15=?' },
      { type: 'fill', q: '500 mL = ? cm³', ans: '500', hint: '1 mL = 1 cm³' },
    ],
  },
  {
    id: 'math-6-13',
    subject: 'math',
    grade: 6,
    chapter: 13,
    title: 'โจทย์ปัญหาประยุกต์',
    icon: '🏆',
    slug: 'applied-problems',
    explain: [
      { type: 'text', html: '<p>การแก้โจทย์ปัญหาระดับสูง:<br/>1. <strong>ตั้งตัวแปร</strong>: ให้ x = ?<br/>2. <strong>ตั้งสมการ</strong>: จากเงื่อนไขในโจทย์<br/>3. <strong>แก้สมการ</strong><br/>4. <strong>ตอบ</strong>: ตรวจสอบและตอบให้ครบ</p>' },
      { type: 'highlight', text: 'โจทย์ระยะทาง: ระยะ = ความเร็ว × เวลา | โจทย์งาน: งาน = อัตรา × เวลา' },
      { type: 'example', text: 'รถ A ออกก่อน 2 ชั่วโมง วิ่ง 60 km/h รถ B วิ่ง 90 km/h เริ่มพร้อมกับ B จะตาม A ทัน... เวลา: ระยะ A = ระยะ B → 60(t+2) = 90t → t = 4 ชั่วโมง' },
    ],
    demo: {
      component: 'BalanceDrag',
      config: {},
      steps: [
        { instruction: 'ตั้งสมการ: ให้ x = จำนวนที่ไม่ทราบ' },
        { instruction: 'โจทย์: ผลรวมสองจำนวน = 50 จำนวนหนึ่งมากกว่าอีก 8 หาจำนวนทั้งสอง', config: { initialLeft: [50] } },
        { instruction: 'ตั้งสมการ: x + (x+8) = 50 → 2x = 42 → x = 21, x+8 = 29' },
        { instruction: 'ตรวจ: 21+29=50 ✓, 29-21=8 ✓' },
      ],
    },
    practice: [
      { type: 'fill', q: 'ผลรวมสองจำนวนคือ 85 จำนวนใหญ่กว่าจำนวนเล็ก 15 จำนวนเล็ก = ?', ans: '35', hint: '2x+15=85, x=35' },
      { type: 'fill', q: 'รถวิ่ง 90 km/h เป็นเวลา 2.5 ชั่วโมง วิ่งได้ ? km', ans: '225', hint: '90×2.5=?' },
      { type: 'mc', q: 'ทำงานร่วมกัน A ทำได้ 10 วัน B ทำได้ 15 วัน ร่วมกันกี่วัน?', opts: ['4', '5', '6', '7'], ans: 2, hint: '1/10+1/15=5/30=1/6 → 6 วัน' },
      { type: 'fill', q: 'ลดราคา 3 ครั้งครั้งละ 10% ราคาเดิม 1,000 บาท ราคาสุดท้าย?', ans: '729', hint: '1000×0.9³=1000×0.729=?' },
      { type: 'fill', q: 'น้ำ 2 ท่อ ท่อ A เติม 20 นาที ท่อ B ระบาย 30 นาที เปิดพร้อมกัน เต็มใน ? นาที', ans: '60', hint: '1/20-1/30=1/60 → 60 นาที' },
      { type: 'mc', q: 'พ่อแม่ลูกรวม 90 ปี พ่ออายุ 4 เท่าลูก แม่อายุ 3 เท่าลูก ลูก = ?', opts: ['10', '11', '12', '9'], ans: 0, hint: 'ลูก=x, พ่อ=4x, แม่=3x, 8x=90→x=?' },
      { type: 'fill', q: 'ลงทุน 50,000 บาท กำไร 15% ขายหมดได้เงิน?', ans: '57500', hint: '50000×1.15=?' },
      { type: 'fill', q: 'คน A วิ่ง 8 km/h คน B เดิน 4 km/h ออกจากจุดเดียวกัน 30 นาทีห่างกัน ? km', ans: '2', hint: '(8-4)×0.5=?' },
      { type: 'mc', q: 'ถังน้ำ 3/4 เต็ม เติมอีก 15 ลิตร เต็มพอดี ถังจุ ? ลิตร', opts: ['45', '50', '55', '60'], ans: 3, hint: '1/4 ของถัง = 15 ลิตร ทั้งถัง = ?' },
      { type: 'fill', q: 'ดอกเบี้ย 400 บาท ฝาก 2 ปี อัตราดอกเบี้ย 4% ต่อปี เงินต้น = ?', ans: '5000', hint: 'I=P×r×t → 400=P×0.04×2 → P=?' },
    ],
  },
]

export default chapters
